flowchart LR
  I[Intermission<br/>you are going to be<br/>assigned a disruption] -- Hit next --> D{{Assigned disruption<br/>d1, d2, d3 or d4}}
  D --> Q[Answer a few questions<br/>on your own]
  Q --> C[Chat to your friends<br/>with the same disruption]
  C --> G[More questions<br/>with the group]
  G -- Submit --> F[Final screen]
